### ISSUE TITLE
Support for remote storage systems

### ISSUE THREAD

**Issue by eric-czech** [fastlmm/PySnpTools#1]
Hi @CarlKCarlK,

Have you considered adding SnpReader support for file reads from remote storage services (S3, GCS, Azure, etc.), probably via fsspec?  I was curious if you have run into the need for that yourself at all.

**Comment by CarlKCarlK** [comment]
Eric,

Great question!

I didn’t know about fsspec.

PySnpTools also includes an abstract distributed file system (https://fastlmm.github.io/PySnpTools/#module-pysnptools.util.filecache) that sounds somewhat similar to fsspec. It is called “filecache”.

[We used filecache to run FaST-LMM on a Azure cluster. We used 100’s of machines over a couple weeks to do a GWAS on 1,000,000 (simulated) individuals https://www.biorxiv.org/content/10.1101/154682v2. We have a version of the Plink Bed format that can be distributed on any supported remote file system. https://fastlmm.github.io/PySnpTools/#snpreader-distributedbed. Sadly, the Azure module was Python2 & Windows-only. So now filecache supports only local files and fast fileshares.]

There months ago, I did start working on S3 support (Git branch: https://github.com/fastlmm/PySnpTools/tree/aws/pysnptools/util/filecache), but stopped because higher priority work came up.

Now that I know about fsspec, I’d try to use it (perhaps wrapping it for “filecache”) [“Anything you can do, I can do meta.” 😊]. I likely won’t do this until I need to. If anyone else wanted work on it, I’d give them enthusiastic support.


  *   Carl

**Comment by eric-czech** [comment]
Thanks @CarlKCarlK!

Looking forward to chatting with you about it some more this week on our call.  I'd love to hear more about what you had to do for that big simulation -- the subtractions from a global sample variance/covariance matrix (i.e. GtG) for LOCO is nifty.  That aligns well with some of the optimizations we've been exploring in [REGENIE](https://rgcgithub.github.io/regenie/) (they do something similar though it's in a reduced space).

Fwiw, our approach thus far for distributed calcs has been to rewrite PLINK using your tools as [Zarr](https://zarr.readthedocs.io/en/stable/) archives and point Dask at that for computation on a cluster.  The extra filters and compression codecs it offers have been a nice way to get bit-packed PLINK datasets down to a size quite a bit smaller than the native PLINK format (with chunking).  Does the distributedbed format chunk arrays in both dimensions by the way?  Very curious to hear what your experience was like in writing that.

**Comment by CarlKCarlK** [comment]
Eric,


  *   Does the distributedbed format chunk arrays in both dimensions by the way?

DistributedBed just splits data by SNPs and stores each chunk as a Bed file. I didn’t think of trying to compress the Bed files themselves because I assumed they were ready very compressed.

Aside: On a related note, I was astonished by how compressed the UK Biobank BGEN imputed data is: Approximately, 15 distributions (of 3 floats) per byte! I guess imputation implies redundancy that zlib is successfully exploiting.

There is not a lot of code in DistributedBed per se. It just implements the SnpReader abstract interface on top of _MergeSIDS and FileCache. _MergeSIDS treats any set of SNP-split SnpReaders as one SnpReader. FileCache is the abstract distributed file-system library that downloads a file for reading if there is not already a local copy that is up-to-date. (For writing, it uploads a locally-written file when the “with” goes out of scope.)

I look forward to talking with you,

Carl

**Comment by eric-czech** [comment]
> FileCache is the abstract distributed file-system library that downloads a file for reading if there is not already a local copy that is up-to-date. (For writing, it uploads a locally-written file when the “with” goes out of scope.)

I see.  Might be the most practical tact for us to take w/ UKB bgen files too.

That certainly answers all my questions on remote storage, so feel free to close this if you'd like.  Thanks again for all the details @CarlKCarlK!

**Comment by CarlKCarlK** [comment]
Will do.


  *   Carl

p.s. Here is what using a FileCache<https://fastlmm.github.io/PySnpTools/#pysnptools.util.filecache.FileCache> looks like to the programmer.

Reading:
with file_cache.open_read('file1.txt') as local_filename:
...     with open(local_filename,'r') as fp:
...         line = fp.readline()
>>> line

Writing:

with file_cache.open_write('file1.txt') as local_filename:

...     with open(local_filename,'w') as fp:

...         _= fp.write('Hello')

>>> file_cache.load('file1.txt')

'Hello'

Where file_cache is an object specific to some local files or some remote files, etc.

(The tricky part was figuring out how to make a local filename work with/as a context manager.)

There are other parts to FileCache that I’m ambivalent about, but I love “open_read” and “open_write” and would recommend it as an API idea for any similar library.
