### ISSUE TITLE
Suggestion support chromosome str type

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/PySnpTools#2]
Hi,

I have a suggestion  for  an enhancement, to support chromosomes as  string type. Otherwise this error raises:

`File "pysnptools\snpreader\bed.py", line 153, in col_property
    self._open_bed.chromosome.astype("float"),
ValueError: could not convert string to float: 'chr1H'`

Thanks
Stefanie

**Comment by CarlKCarlK** [comment]
Stefanie,

Thank you for using PySnpTools and thanks for your suggestion.

This is something we'd like to do.

For compatibility reasons, the chromosomes will need to be numbers when inside PySnpTools. I'm thinking about using this mapping by default:
X=23
Y=24
XY=25
MT=26
with an option to override. What do you think? (This is based on this section of the PLINK manual<https://zzz.bwh.harvard.edu/plink/data.shtml#map>)


While waiting for this feature, two work arounds are available.

  *   First, if one only needs to read Plink Bed files and isn't using other PySnpTools features, one can use bed-reader * PyPI<https://pypi.org/project/bed-reader/>. This is the library that PySnpTools uses and it supports chromosomes as strings.
  *   Second, one can use a text editor and edit the *.bim file to change non-numeric chromosomes to numeric ones.

Thanks again for your suggestion,
Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via ***@***.***?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>)
From: snowformatics ***@***.***>
Sent: Friday, April 30, 2021 12:43 AM
To: fastlmm/PySnpTools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/PySnpTools] Suggestion support chromosome str type (#2)
Importance: High


Hi,

I have a suggestion for an enhancement, to support chromosomes as string type. Otherwise this error raises:

File "pysnptools\snpreader\bed.py", line 153, in col_property self._open_bed.chromosome.astype("float"), ValueError: could not convert string to float: 'chr1H'

Thanks
Stefanie

-

**Comment by snowformatics** [comment]
Hi Carl,

thanks a lot for your answer (and sorry for my late replay, I work at home with my toddler).

I have used already a work around and it's no problem for me. 

For the mapping, I think it's OK to  support PLINKs defaults options if overriding is possible, e.g. for plants we often a different mapping (for instance wheat with set of sets of six chromosomes).

Just to keep in mind other species :)

Best regards
Stefanie

**Comment by CarlKCarlK** [comment]
I have a new development version of PySnpTools with this feature. Here is the current design:

To install it:

•	pip uninstall pysnptools
•	pip install git+https://github.com/fastlmm/PySnpTools.git@f169f2c

Then you can use Bed() to tell how to read the Bed file including how to interpret non-numeric chromosomes. Here is an example:

```
import numpy as np
from fastlmm.association import single_snp
from fastlmm.util import example_file # Download and return local file name

bed_fn = example_file('tests/datasets/synth/all.*','*.bed')
pheno_fn = example_file("tests/datasets/synth/pheno_10_causals.txt")
cov_fn = example_file("tests/datasets/synth/cov.txt")

###### Use Bed() to tell how to read the Bed file including how to interpret 	non-numeric chromosomes.
from pysnptools.snpreader import Bed
bed = Bed(bed_fn, count_A1=False, chrom_map={"X": 23, "Y": 24, "XY": 25, "MT": 26})

###### Use 'bed' instead of 'bed_fn'
results_df = single_snp(bed, pheno_fn, covar=cov_fn, count_A1=False)
```

The chrom_map tells how to turn any characters in the *.bim file into some number (which is what PySnptools and FaST-LMM need). There is also a "reverse_chrom_map" for Bed.write. By default, this chrom_map given above is used when reading, but there is no default reverse_chrom_map for writing.

**Comment by snowformatics** [comment]
Great news, I will try ASAP and report feedback!

Thanks
Stefanie

Am Do., 24. Juni 2021 um 02:10 Uhr schrieb Carl Kadie <
***@***.***>:
